### ISSUE TITLE
[Bug]: Overwrite Gate not working

### ISSUE THREAD

**Issue by giacomomasseron** [scalar/laravel#8]
### What happened?

Hi,  
I'm trying to overwrite the Gate definition in the `AppServiceProvider` file, but I get this error:

```
{
    "error": {
    "message": ""
},
"result": {
    "error": ""
},
```

I just put this in AppServiceProvider boot function:

```
Gate::define('viewScalar', function ($user) {
    return false;
});
```

P.S. I'm in local but I put "staging" in my .env file, to test it.

### How to reproduce the bug

I:

- installed the package
- changed .env value to staging
- ovewritten Gate definition

### Package Version

0.2.0

### PHP Version

8.3.0

### Laravel Version

11.45.1

**Comment by hanspagel** [comment]
Mhh… Did you try to make the $user parameter optional?

**Comment by giacomomasseron** [comment]
Yes, that was it. Maybe you should change docs?

**Comment by hanspagel** [comment]
Yess! I updated the README.

**Comment by rdp77** [comment]
I'm using this code in the staging environment, but I'm still getting a 403 error. Even after I deleted the overwritten files, the result remained the same. This only happens in environments other than the local environment.

```
   Gate::define('viewScalar', static function () {
            return true;
        });
```

And I also checked it in Tinker, and the result was always "false"; it should be "true."

```
❯ php artisan tinker    
Psy Shell v0.12.24 (PHP 8.2.33 — cli) by Justin Hileman
New PHP manual is available (latest: 3.0.0). Update with `doc --update-manual`
> Gate::check('viewScalar')

= false
```
